# Generated by Django 4.2.1 on 2023-05-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='record',
            name='prescription',
            field=models.TextField(blank=True, null=True, verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='record',
            name='meeting_date',
            field=models.DateTimeField(default=None, verbose_name='Meeting date of users.'),
        ),
    ]
