name: hackapp
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_svg: ^1.0.0
  animate_do: ^2.0.0
  salomon_bottom_bar: ^3.1.0
  flutter_staggered_grid_view: ^0.4.0
  hexcolor: ^2.0.5
  group_button: ^4.1.0
  table_calendar: ^3.0.3
  jiffy: ^5.0.0
  flutter_bloc: ^8.0.0
  uuid: ^3.0.7
  shortid: ^0.1.2
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
  # Add assets from the images directory to the application.
  - assets/images/
